name: Deploy AKS-Construction

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  create_resource_group_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Resource Group
        id: create_rg
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.LOCATION }}
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          RESOURCE_GROUP_NAME: rg-k8s-pygoat-dev-001
          LOCATION: canadacentral
  reusable_workflow_job:
    uses: Azure/AKS-Construction/.github/workflows/AKSC_Deploy.yml@0.10.5
    with:
      templateVersion: 0.10.5
      rg: rg-k8s-pygoat-dev-001
      resourceName: k8s-pygoat-dev-001
      templateParams: resourceName=k8s-pygoat-dev-001 agentCount=1 upgradeChannel=stable JustUseSystemPool=true agentCountMax=20 osDiskType=Managed osDiskSizeGB=32 enableTelemetry=false omsagent=true retentionInDays=30 ingressApplicationGateway=true automationAccountScheduledStartStop=Weekday
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      USER_OBJECT_ID: ${{ secrets.USER_OBJECT_ID }}
