name: Deploy AKS-Construction

on:
  workflow_dispatch:

permissions:
  id-token: write #This is required for requesting the JWT
  contents: write # This is required to create/push the new git tag

jobs:
  create_resource_group_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Create Resource Group
        id: create_rg
        run: |
          az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.LOCATION }}
        env:
          RESOURCE_GROUP_NAME: rg-k8s-pygoat-dev-001
          LOCATION: canadacentral
  reusable_workflow_job:
    uses: Azure/AKS-Construction/.github/workflows/AKSC_Deploy.yml@0.10.5
    needs: create_resource_group_job
    with:
      templateVersion: 0.10.5
      rg: rg-k8s-pygoat-dev-001
      resourceName: k8s-pygoat-dev-001
      templateParams: resourceName=k8s-pygoat-dev-001 agentCount=1 upgradeChannel=stable JustUseSystemPool=true agentCountMax=20 osDiskType=Managed osDiskSizeGB=32 enableTelemetry=false omsagent=true retentionInDays=30 ingressApplicationGateway=true automationAccountScheduledStartStop=Weekday
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      USER_OBJECT_ID: ${{ secrets.USER_OBJECT_ID }}
